### ISSUE TITLE
Error "Rendezvous of RPC that terminated - failed to connect to all addresse"

### ISSUE THREAD

**Issue by jmorel** [SubstraFoundation/substra-backend#77] opened 2019-12-11 08:10 UTC
While trying to add a bunch of assets, I regularly end up with the following message (as returned by the SDK):

```
ERROR    substra.sdk.rest_client:rest_client.py:116 Requests error status 400: {"message":"<_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"failed to connect to all addresses\"\n\tdebug_error_string = \"{\"created\":\"@1576051644.524371597\",\"description\":\"Failed to pick subchannel\",\"file\":\"src/core/ext/filters/client_channel/client_channel.cc\",\"file_line\":3934,\"referenced_errors\":[{\"created\":\"@1576051644.524366407\",\"description\":\"failed to connect to all addresses\",\"file\":\"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc\",\"file_line\":393,\"grpc_status\":14}]}\"\n>"}
```

**Comment by samlesu** [comment] 2019-12-11 10:29
Thanks @jmorel do you have the associated traceback in the backend?

**Comment by Kelvin-M** [comment] 2020-01-07 08:59
@jmorel Do you manage to reproduce it ? It would be nice to have the backend traceback in order to be able to find a fix for this issue.
I suspect that we will need to change the way we initialize the fabric client !

**Comment by jmorel** [comment] 2020-01-07 16:14
I used to have the issue while creating assets on the demo setup, I tried reproducing it locally but can't. I'll run my test case against the demo as soon as it's available again and fetch the traceback.

**Comment by jmorel** [comment] 2020-01-08 10:24
I got the error again while running a very big (about 1400 tuples) compute plan on the demo env, here is the stacktrace from org4-worker:

```
[2020-01-08 08:04:52,559: ERROR/ForkPoolWorker-1] <_Rendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses"
    debug_error_string = "{"created":"@1578470692.558659550","description":"Failed to pick subchannel","file":"src/core/ext/filters
/client_channel/client_channel.cc","file_line":3934,"referenced_errors":[{"created":"@1578470692.558654186","description":"failed t
o connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_s
tatus":14}]}"
>
Traceback (most recent call last):
  File "/usr/src/app/substrapp/ledger_utils.py", line 167, in call_ledger
    response = loop.run_until_complete(chaincode_calls[call_type](**params))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/hfc/fabric/client.py", line 1640, in chaincode_invoke
    res = await asyncio.gather(*responses)
  File "/usr/local/lib/python3.6/dist-packages/aiogrpc/channel.py", line 40, in __call__
    return await fut
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses"
    debug_error_string = "{"created":"@1578470692.558659550","description":"Failed to pick subchannel","file":"src/core/ext/filters
/client_channel/client_channel.cc","file_line":3934,"referenced_errors":[{"created":"@1578470692.558654186","description":"failed t
o connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_s
tatus":14}]}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/substrapp/ledger_utils.py", line 180, in call_ledger
    response = [r for r in e.args[0] if r.response.status != 200][0].response.message
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/substrapp/tasks/tasks.py", line 472, in on_success
    log_success_tuple(tuple_type, subtuple['key'], retval['result'])
  File "/usr/src/app/substrapp/ledger_utils.py", line 371, in log_success_tuple
    _update_tuple_status(tuple_type, tuple_key, 'done', extra_kwargs=extra_kwargs)
  File "/usr/src/app/substrapp/ledger_utils.py", line 324, in _update_tuple_status
    update_ledger(fcn=invoke_fcn, args=invoke_args, sync=True)
  File "/usr/src/app/substrapp/ledger_utils.py", line 107, in _wrapper
    return fn(*args, **kwargs)
  File "/usr/src/app/substrapp/ledger_utils.py", line 233, in update_ledger
    return _invoke_ledger(*args, **kwargs)
  File "/usr/src/app/substrapp/ledger_utils.py", line 212, in _invoke_ledger
    response = call_ledger('invoke', fcn=fcn, args=args, kwargs=params)
  File "/usr/src/app/substrapp/ledger_utils.py", line 182, in call_ledger
    raise LedgerError(str(e))
substrapp.ledger_utils.LedgerError: <_Rendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "failed to connect to all addresses"
    debug_error_string = "{"created":"@1578470692.558659550","description":"Failed to pick subchannel","file":"src/core/ext/filters
/client_channel/client_channel.cc","file_line":3934,"referenced_errors":[{"created":"@1578470692.558654186","description":"failed t
o connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":393,"grpc_s
tatus":14}]}"
>
```

**Comment by Kelvin-M** [comment] 2020-01-08 10:34
Thank you @jmorel.
We can see that we do not retry on this kind of error https://github.com/SubstraFoundation/substra-backend/blob/master/backend/substrapp/ledger_utils.py#L89-L117
We can a new error to retry on this issue

**Comment by samlesu** [comment] 2020-01-08 10:44
Thanks @jmorel, this is clearer and it seems like a new error.

As seen in the traceback, the backend is also failing to parse correctly this error (should be fixed).

Before retrying on this error, I think it would be worth to understand the cause of this error. Retrying may not be the only solution and not the best long term solution.

**Comment by Kelvin-M** [comment] 2020-01-24 09:09
Where are we on this one ?
As we have a ledger retry strategy it should prevent from short connection interruption between two nodes. For longer interruption, it may be a bigger problem that should not be handled directly in the backend no ?

**Comment by GuillaumeCisco** [comment] 2020-02-05 16:28
I've just written a document about this error.
It is available [here](https://github.com/SubstraFoundation/substra-backend/blob/test-grpc-failure/gRPC%20error%2014.md)

Please give me your reviews on it.

**Closed** 2020-02-25 16:19 UTC
Labels: bug
